/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.ridgway.paul.tests.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Event implements org.apache.thrift.TEnum {
  TEST_RUN_STARTED(0),
  TEST_RUN_FINISHED(1),
  TEST_STARTED(2),
  TEST_FINISHED(3),
  TEST_FAILURE(4),
  TEST_ASSUMPTION_FAILURE(5),
  TEST_IGNORED(6);

  private final int value;

  private Event(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Event findByValue(int value) { 
    switch (value) {
      case 0:
        return TEST_RUN_STARTED;
      case 1:
        return TEST_RUN_FINISHED;
      case 2:
        return TEST_STARTED;
      case 3:
        return TEST_FINISHED;
      case 4:
        return TEST_FAILURE;
      case 5:
        return TEST_ASSUMPTION_FAILURE;
      case 6:
        return TEST_IGNORED;
      default:
        return null;
    }
  }
}
